---
title: "EDA Carrera Luz"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(paqueteMET)
library(tidyverse)
library(plotly)
library(correlationfunnel)
library(ggdist)
library(tidyquant)
```

```{r}
carrera_ext <- CarreraLuz22 %>% 
  mutate(median_t = median(timerun),
         over_median = if_else(timerun>median_t, "yes", "no")) %>% 
  select(-id, -median_t,-timerun)

bin_car <- carrera_ext %>% 
  binarize(n_bins = 5)

correlated_carrera <- bin_car %>%
  correlate(target = over_median__yes)
```


Exploración Inicial {data-navmenu="Menu"}
==================================


Column {data-width=250}
-----------------------------------------------------------------------
### Time Run

```{r}
ggplot(CarreraLuz22 , aes( y = timerun)) +
  stat_halfeye(adjust = 0.5,
               justification = -0.2,
               .width = 0,
               point_colour = NA,
               fill = "#1F78B4") +
  geom_boxplot(
    width = 0.12,
    outlier.color = NA,
    alpha = 0.5,
    fill = "#1F78B4"
  ) +
  stat_dots(
    side = "left",
    justification = 1.1,
    fill = "#1F78B4"
  ) +
  coord_flip() +
  theme_tq() +
  scale_fill_tq(theme = "light") +
  theme(axis.text.y=element_blank()
        ) +
  xlab("")
```



### Sex
```{r}
g <- ggplot(CarreraLuz22 , aes(x = sex, fill = sex)) +
  geom_bar() +
  theme_tq() +
  scale_fill_tq(theme = "light") +
  theme(legend.position = "none") +
  coord_flip() +
  xlab("") 
  

ggplotly(g)
```

Column {data-width=250}
-----------------------------------------------------------------------
### Edad
```{r}
ggplot(CarreraLuz22 , aes( y = edad)) +
  stat_halfeye(adjust = 0.5,
               justification = -0.2,
               .width = 0,
               point_colour = NA,
               fill = "#2C3E50") +
  geom_boxplot(
    width = 0.12,
    outlier.color = NA,
    alpha = 0.5,
    fill = "#2C3E50"
  ) +
  stat_dots(
    side = "left",
    justification = 1.1,
    fill = "#2C3E50"
  ) +
  coord_flip() +
  theme_tq() +
  scale_fill_tq(theme = "light") +
  theme(axis.text.y=element_blank()) +
  xlab("") 

```

### Categoria

```{r}
g <- ggplot(CarreraLuz22 %>% 
              mutate(
           categoria = fct_infreq(categoria)), 
            aes(x = categoria, fill = categoria)) +
  geom_bar() +
  theme_tq() +
  scale_fill_tq(theme = "light") +
  theme(legend.position = "none") +
  coord_flip() +
  xlab("") 

ggplotly(g)
```


Column {data-width=250}
-----------------------------------------------------------------------
### Origen

```{r}
g <- ggplot(CarreraLuz22 %>% 
              mutate(
           origen = fct_infreq(origen),
           origen = fct_lump_lowfreq(origen, other_level = "Otros 48 Origenes")), 
            aes(x = origen, fill = origen)) +
  geom_bar() +
  theme_tq() +
  scale_fill_tq(theme = "light") +
  theme(legend.position = "none") +
  coord_flip() +
  xlab("") 

ggplotly(g)
```

### Nacionalidad

```{r}
g <- ggplot(CarreraLuz22 %>% 
              mutate(
           nacionalidad = fct_infreq(nacionalidad),
           nacionalidad = fct_lump_lowfreq(nacionalidad, other_level = "Otras 5 Nacionalidades")
           ), 
            aes(x = nacionalidad, fill = nacionalidad)) +
  geom_bar() +
  theme_tq() +
  scale_fill_tq(theme = "light") +
  theme(legend.position = "none") +
  coord_flip() +
  xlab("") 

ggplotly(g)
```

Column {data-width=250}
-----------------------------------------------------------------------
### Discusión





Ingeniería de características {data-navmenu="Menu"}
==================================
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
g <- correlated_carrera %>%
    filter(!(feature %in% c("over_median"))) %>%
    plot_correlation_funnel(interactive = FALSE, limits = c(-0.5, 0.5))

g2 <- g + ggtitle("Funnel de correlación, Tiempo Bajo la Mediana / Tiempo Sobre la Mediana")

ggplotly(g2)
  
```

Exploración Inicial {data-navmenu="Menu"}
==================================

### Chart B

```{r}
g <- ggplot(CarreraLuz22, aes(edad, timerun, color = sex)) +
  geom_point(alpha = 0.5)

ggplotly(g)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart C

```{r}

ggplot(CarreraLuz22 %>%
         filter(timerun != max(timerun)), aes(x = sex, y = timerun, fill = sex)) +
  stat_halfeye(adjust = 0.5,
               justification = -0.2,
               .width = 0,
               point_colour = NA) +
  geom_boxplot(
    width = 0.12,
    outlier.color = NA,
    alpha = 0.5
  ) +
  stat_dots(
    side = "left",
    justification = 1.1
  ) +
  coord_flip() +
  theme_tq() +
  scale_fill_tq(theme = "light")




```

### Chart D

```{r}
ggplot(CarreraLuz22 %>%
         mutate(
           rango_edad = cut_number(edad, 5)) %>% 
         filter(timerun != max(timerun)#,
                #sex == "Mujer"
                ) %>% 
         mutate(
           rango_edad = fct_reorder(rango_edad, timerun, median)), 
       aes(x = rango_edad, y = timerun, fill = rango_edad)) +
  stat_halfeye(adjust = 0.5,
               justification = -0.2,
               .width = 0,
               point_colour = NA) +
  geom_boxplot(
    width = 0.12,
    outlier.color = NA,
    alpha = 0.5
  ) +
  stat_dots(
    side = "left",
    justification = 1.1
  ) +
  coord_flip() +
  theme_tq() +
  scale_fill_tq(theme = "light")
```

